blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/floating-ui/floating-ui/discussions
    about: If you can't get something to work, open a question in our discussion forums.
  - name: Feature Request
    url: https://github.com/floating-ui/floating-ui/discussions/new?category=ideas
    about: Suggest any ideas you have using our discussion forums.
